apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  nodeName: 'node04'
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.0-devel
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
