# In order to run this, do:
# docker-compose -f container_stack.yml up
version: '3.1'

services:
  web:
    image: orchestra/web
    restart: unless-stopped
    network_mode: "host"
    volumes:
        - /mnt/cluster-volume:/mnt/cluster-volume
        - /home/rancher:/home/rancher
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
  
  api:
    image: orchestra/api
    restart: unless-stopped
    network_mode: "host"
    volumes:
        - /mnt/cluster-volume:/mnt/cluster-volume
        - /home/rancher:/home/rancher
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02

  main:
    image: orchestra/main
    restart: unless-stopped
    network_mode: "host"
    volumes:
        - /mnt/cluster-volume:/mnt/cluster-volume
        - /home/rancher:/home/rancher
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
